# Generated by Django 3.2.7 on 2022-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_partners_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='partners',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, null=True, upload_to='partner_pics'),
        ),
    ]
